spring.application.name=demo

server.port=9992

spring.data.mongodb.database=devop-1
spring.data.mongodb.uri=mongodb://

keycloak.auth-server-url=http://localhost:8080
keycloak.realm=devop-realm
keycloak.client-id=vue-app
keycloak.client-secret=Ob0i4PRDA3rQ3kedHLTGZ13viE0zYrRm
keycloak.redirect-uri=http://localhost:5173/

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/devop-1

minio.endpoint=http://127.0.0.1:9000
minio.access-key=phudvq
minio.secret-key=Ph12345678!
minio.bucket-name=devop-1

# EventStoreDB connection string must use the 'esdb' scheme (not http)
# For a local non-TLS EventStoreDB instance use: esdb://host:port?tls=false
kurrentdb.connection-string=esdb://127.0.0.1:2113?tls=false
